db.games.insert({ 'title' : "God Of War Chains Of Olympus", 'cost' : 750, 'user_rating' :91, 'pegi_rating' :18, 'platforms' : ['PSP']});
db.games.insert({ 'title' : "God Of War 1", 'cost' : 420, 'user_rating' :94, 'pegi_rating' :18, 'platforms' : ['PS3']});
db.games.insert({ 'title' : "God Of War Ghost of Sparta", 'cost' : 850, 'user_rating' :86, 'pegi_rating' :18, 'platforms' : ['PSP']});
db.games.insert({ 'title' : "God Of War 2", 'cost' : 999, 'user_rating' :93, 'pegi_rating' :18, 'platforms' : ['PS3']});
db.games.insert({ 'title' : "God of War 3", 'cost' : 950, 'user_rating' :92, 'pegi_rating' :18, 'platforms' : ['PS3']});
db.games.insert({ 'title' : "Prince of Persia - The Sands of Time", 'cost' : 690, 'user_rating' :89, 'pegi_rating' :12, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Prince of Persia - Warrior Within", 'cost' : 700, 'user_rating' :83, 'pegi_rating' :12, 'platforms' : ['PC','PS3','PSP']});
db.games.insert({ 'title' : "Prince of Persia The Two Thrones", 'cost' : 750, 'user_rating' :85, 'pegi_rating' :12, 'platforms' : ['PC','PS3','PSP']});
db.games.insert({ 'title' : "Max Payne 1", 'cost' : 999, 'user_rating' :89, 'pegi_rating' :16, 'platforms' : ['PC','PS2']});
db.games.insert({ 'title' : "Max Payne 2 - The Fall of Max Payne", 'cost' : 1499, 'user_rating' :86, 'pegi_rating' :16, 'platforms' : ['PC','PS2']});
db.games.insert({ 'title' : "Max Payne 3", 'cost' : 999, 'user_rating' :86, 'pegi_rating' :16, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "Counter Strike - 1.6", 'cost' : 600, 'user_rating' :83, 'pegi_rating' :12, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Counter Strike - Source", 'cost' : 480, 'user_rating' :88, 'pegi_rating' :12, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Counter Strike - Condition Zero", 'cost' : 500, 'user_rating' :65, 'pegi_rating' :12, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Borderlands 1", 'cost' : 1720, 'user_rating' :84, 'pegi_rating' :16, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Borderlands 2", 'cost' : 2200, 'user_rating' :89, 'pegi_rating' :16, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Hitman 1", 'cost' : 1000, 'user_rating' :82, 'pegi_rating' :18, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Hitman 2", 'cost' : 820, 'user_rating' :83, 'pegi_rating' :18, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Need For Speed - Underground", 'cost' : 750, 'user_rating' :82, 'pegi_rating' :16, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Need For Speed - Underground 2", 'cost' : 800, 'user_rating' :82, 'pegi_rating' :16, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Need For Speed - Most Wanted", 'cost' : 699, 'user_rating' :83, 'pegi_rating' :16, 'platforms' : ['PC','PS2','PS3','XBOX360']});
db.games.insert({ 'title' : "Need For Speed - Carbon", 'cost' : 799, 'user_rating' :78, 'pegi_rating' :16, 'platforms' : ['PC','PS2','PS3','XBOX360']});
db.games.insert({ 'title' : "Unreal Tournament - GOTY", 'cost' : 2000, 'user_rating' :84, 'pegi_rating' :18, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Unreal Tournament - 2003", 'cost' : 1300, 'user_rating' :83, 'pegi_rating' :18, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Unreal Tournament - 2004", 'cost' : 1500, 'user_rating' :85, 'pegi_rating' :18, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Unreal Tournament - 2007", 'cost' : 1800, 'user_rating' :86, 'pegi_rating' :18, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "Heavy Rain", 'cost' : 950, 'user_rating' :87, 'pegi_rating' :12, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "Asuras Wrath", 'cost' : 1000, 'user_rating' :80, 'pegi_rating' :18, 'platforms' : ['PS3','XBOX360']});
db.games.insert({ 'title' : "Age of Empire", 'cost' : 750, 'user_rating' :83, 'pegi_rating' :16, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Portal 1", 'cost' : 1300, 'user_rating' :90, 'pegi_rating' :16, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "Portal 2", 'cost' : 1200, 'user_rating' :95, 'pegi_rating' :16, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "F1 2009", 'cost' : 1100, 'user_rating' :69, 'pegi_rating' :7, 'platforms' : ['PS3','XBOX360','PSP']});
db.games.insert({ 'title' : "F1 2011", 'cost' : 1200, 'user_rating' :79, 'pegi_rating' :7, 'platforms' : ['PS3','XBOX360','PSP']});
db.games.insert({ 'title' : "F1 2012", 'cost' : 1400, 'user_rating' :80, 'pegi_rating' :7, 'platforms' : ['PS3','XBOX360','PSP']});
db.games.insert({ 'title' : "Burnout - Legends", 'cost' : 750, 'user_rating' :86, 'pegi_rating' :18, 'platforms' : ['PSP']});
db.games.insert({ 'title' : "Burnout - Dominator", 'cost' : 850, 'user_rating' :76, 'pegi_rating' :18, 'platforms' : ['PS2','PSP']});
db.games.insert({ 'title' : "Resistance 1 - Fall of Man", 'cost' : 1200, 'user_rating' :86, 'pegi_rating' :16, 'platforms' : ['PS3']});
db.games.insert({ 'title' : "Resistance 2", 'cost' : 1300, 'user_rating' :87, 'pegi_rating' :16, 'platforms' : ['PS3']});
db.games.insert({ 'title' : "Resistance 3", 'cost' : 1700, 'user_rating' :83, 'pegi_rating' :16, 'platforms' : ['PS3']});
db.games.insert({ 'title' : "Resistance Retribution", 'cost' : 1500, 'user_rating' :81, 'pegi_rating' :16, 'platforms' : ['PSP']});
db.games.insert({ 'title' : "Cricket 2012", 'cost' : 700, 'user_rating' :79, 'pegi_rating' :3, 'platforms' : ['PC','XBOX360']});
db.games.insert({ 'title' : "Cricket 2010", 'cost' : 500, 'user_rating' :66, 'pegi_rating' :3, 'platforms' : ['PC','XBOX360']});
db.games.insert({ 'title' : "Darkness 1", 'cost' : 1300, 'user_rating' :79, 'pegi_rating' :16, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "Darkness 2", 'cost' : 1350, 'user_rating' :80, 'pegi_rating' :16, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "Fifa 2012", 'cost' : 850, 'user_rating' :86, 'pegi_rating' :3, 'platforms' : ['PC','PS3']});
db.games.insert({ 'title' : "NBA 2012", 'cost' : 600, 'user_rating' :90, 'pegi_rating' :3, 'platforms' : ['PC','PS3']});
db.games.insert({ 'title' : "PGA 2012", 'cost' : 450, 'user_rating' :75, 'pegi_rating' :3, 'platforms' : ['PCPS3','XBOX360']});
db.games.insert({ 'title' : "Grand Theft Auto - Vice City", 'cost' : 599, 'user_rating' :95, 'pegi_rating' :18, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Grand Theft Auto - San Andreas", 'cost' : 699, 'user_rating' :95, 'pegi_rating' :18, 'platforms' : ['PC']});
db.games.insert({ 'title' : "Syndicate wars", 'cost' : 1000, 'user_rating' :78, 'pegi_rating' :18, 'platforms' : ['PC','PS3','XBOX360']});
db.games.insert({ 'title' : "Red Dead Redemption", 'cost' : 850, 'user_rating' :95, 'pegi_rating' :18, 'platforms' : ['PS3','XBOX360']});
db.games.insert({ 'title' : "Bioshock Infinite", 'cost' : 1250, 'user_rating' :94, 'pegi_rating' :16, 'platforms' : ['PS3','XBOX360']});
db.games.insert({ 'title' : "Bioshock 1", 'cost' : 900, 'user_rating' :96, 'pegi_rating' :16, 'platforms' : ['PS3','XBOX360']});
db.games.insert({ 'title' : "Bioshock 2", 'cost' : 800, 'user_rating' :98, 'pegi_rating' :16, 'platforms' : ['PS3','XBOX360']});
